###########################
## COMMON
COMMONNODENAME = None

UTILS_MENUNAME = "UTILS"
UTILSID = 1
UTILS_ISRADIAL = False

COPYID = 10
COPY_MENUNAME = "copyNodes"
COPY_ISRADIAL = False

PASTEID = 11
PASTE_MENUNAME = "pasteNodes"
PASTE_ISRADIAL = False

###########################
## HERMITE
HA_NODENAME = "jd_hermiteArrayCrv"

HASOUTH = 100
HASOUTH_MENUNAME = "Create OutputJoints"
HASOUTH_ISRADIAL = True
HASOUTH_RADIALPOS = "S"

HANORTH = 101
HANORTH_MENUNAME = "TEST"
HANORTH_ISRADIAL = True
HANORTH_RADIALPOS = "N"
